import Foundation

enum CodexUsageError: Error, Equatable {
    case codexNotInstalled
    case processFailed
    case decoding
    case timeout
}

/// `codex app-server`'s JSON-RPC-over-stdio protocol, verified live against the schema
/// generated by `codex app-server generate-json-schema`: the default transport is
/// `stdio://` (no daemon or control socket required), and `account/rateLimits/read`
/// returns the account's current rate-limit snapshot directly, so a fresh process is
/// spawned per refresh and torn down immediately after — no persistent background process.
actor CodexAppServerClient {
    private static let requestTimeout: TimeInterval = 15

    func fetchRateLimits() async throws -> CodexAccountRateLimits {
        guard let codexPath = Self.resolveCodexExecutablePath() else {
            throw CodexUsageError.codexNotInstalled
        }

        let process = Process()
        process.executableURL = URL(fileURLWithPath: codexPath)
        process.arguments = ["app-server"]

        let stdinPipe = Pipe()
        let stdoutPipe = Pipe()
        let stderrPipe = Pipe()
        process.standardInput = stdinPipe
        process.standardOutput = stdoutPipe
        process.standardError = stderrPipe

        let collector = JSONRPCLineCollector()
        stdoutPipe.fileHandleForReading.readabilityHandler = { handle in
            let data = handle.availableData
            guard !data.isEmpty else { return }
            collector.append(data)
        }

        defer {
            stdoutPipe.fileHandleForReading.readabilityHandler = nil
            if process.isRunning {
                process.terminate()
            }
        }

        do {
            try process.run()
        } catch {
            throw CodexUsageError.processFailed
        }

        let stdin = stdinPipe.fileHandleForWriting
        do {
            try Self.send(["id": 1, "method": "initialize", "params": [
                "clientInfo": ["name": "AgentLimits", "title": "AgentLimits", "version": "0.1.0"],
            ]], to: stdin)
            try Self.send(["method": "initialized", "params": NSNull()], to: stdin)
            try Self.send(["id": 2, "method": "account/rateLimits/read", "params": NSNull()], to: stdin)
        } catch {
            throw CodexUsageError.processFailed
        }

        do {
            let responseData = try await Self.withTimeout(Self.requestTimeout) {
                try await collector.waitForResponse(id: 2)
            }
            return try JSONDecoder()
                .decode(JSONRPCResultEnvelope<CodexAccountRateLimits>.self, from: responseData)
                .result
        } catch is DecodingError {
            throw CodexUsageError.decoding
        } catch let error as CodexUsageError {
            throw error
        } catch {
            throw CodexUsageError.timeout
        }
    }

    private static func send(_ object: [String: Any], to handle: FileHandle) throws {
        var line = try JSONSerialization.data(withJSONObject: object)
        line.append(0x0A)
        handle.write(line)
    }

    private static func withTimeout<T: Sendable>(
        _ seconds: TimeInterval,
        operation: @escaping @Sendable () async throws -> T
    ) async throws -> T {
        try await withThrowingTaskGroup(of: T.self) { group in
            group.addTask { try await operation() }
            group.addTask {
                try await Task.sleep(for: .seconds(seconds))
                throw CodexUsageError.timeout
            }
            guard let result = try await group.next() else {
                throw CodexUsageError.timeout
            }
            group.cancelAll()
            return result
        }
    }

    /// A GUI app launched via LaunchServices (Dock/Finder double-click, `open`) inherits a
    /// minimal PATH that does not include a shell's `.zshrc`/`.zprofile` additions — where
    /// `codex` commonly lives (e.g. `~/.local/bin`, mise/asdf shims, nvm). `ProcessInfo`'s
    /// PATH alone is therefore not enough; common user-local install locations are checked
    /// first, and as a last resort a login shell is asked to resolve it the way a terminal
    /// would (`command -v`), covering PATH customizations this app cannot otherwise predict.
    private static func resolveCodexExecutablePath() -> String? {
        let home = FileManager.default.homeDirectoryForCurrentUser.path
        let commonPaths = [
            "\(home)/.local/bin/codex",
            "/opt/homebrew/bin/codex",
            "/usr/local/bin/codex",
            "\(home)/.local/share/mise/shims/codex",
        ]
        for path in commonPaths where FileManager.default.isExecutableFile(atPath: path) {
            return path
        }

        if let pathEnv = ProcessInfo.processInfo.environment["PATH"] {
            for dir in pathEnv.split(separator: ":") {
                let candidate = "\(dir)/codex"
                if FileManager.default.isExecutableFile(atPath: candidate) {
                    return candidate
                }
            }
        }

        return resolveViaLoginShell()
    }

    private static func resolveViaLoginShell() -> String? {
        let shell = ProcessInfo.processInfo.environment["SHELL"] ?? "/bin/zsh"
        let process = Process()
        process.executableURL = URL(fileURLWithPath: shell)
        process.arguments = ["-l", "-c", "command -v codex"]
        let pipe = Pipe()
        process.standardOutput = pipe
        process.standardError = Pipe()

        do {
            try process.run()
        } catch {
            return nil
        }
        process.waitUntilExit()

        guard process.terminationStatus == 0 else { return nil }
        let data = pipe.fileHandleForReading.readDataToEndOfFile()
        guard let path = String(data: data, encoding: .utf8)?
            .trimmingCharacters(in: .whitespacesAndNewlines), !path.isEmpty,
            FileManager.default.isExecutableFile(atPath: path)
        else { return nil }
        return path
    }
}

private struct JSONRPCResultEnvelope<T: Decodable>: Decodable {
    let result: T
}

/// Buffers stdout bytes from the spawned process, splits them into newline-delimited
/// JSON-RPC lines, and lets callers await a specific response `id`. Fed from the
/// `Pipe`'s `readabilityHandler`, which runs on a background dispatch queue outside the
/// client actor, so this uses its own serial queue rather than actor isolation.
private final class JSONRPCLineCollector: @unchecked Sendable {
    private let queue = DispatchQueue(label: "it.stefer.AgentLimits.jsonrpc-collector")
    private var buffer = Data()
    private var pendingResponses: [Int: Data] = [:]
    private var continuations: [Int: CheckedContinuation<Data, Error>] = [:]

    func append(_ data: Data) {
        queue.async {
            self.buffer.append(data)
            while let newlineIndex = self.buffer.firstIndex(of: 0x0A) {
                let lineData = self.buffer.subdata(in: self.buffer.startIndex..<newlineIndex)
                self.buffer.removeSubrange(self.buffer.startIndex...newlineIndex)
                self.handleLine(lineData)
            }
        }
    }

    private func handleLine(_ lineData: Data) {
        guard !lineData.isEmpty,
              let object = try? JSONSerialization.jsonObject(with: lineData) as? [String: Any],
              let id = object["id"] as? Int
        else { return }

        if let continuation = continuations.removeValue(forKey: id) {
            continuation.resume(returning: lineData)
        } else {
            pendingResponses[id] = lineData
        }
    }

    func waitForResponse(id: Int) async throws -> Data {
        try await withCheckedThrowingContinuation { continuation in
            queue.async {
                if let data = self.pendingResponses.removeValue(forKey: id) {
                    continuation.resume(returning: data)
                } else {
                    self.continuations[id] = continuation
                }
            }
        }
    }
}
